[splunk_gnomeification]
is_custom = 1
label = GNOME Desktop Notification
description = Sends a GNOME desktop notification when an alert fires.
param.message = Message to display
param.title = Notification title
script = splunk_gnomeification.py
