[splunk_gnomeification]
is_custom = 1
label = Splunk Gnomeification
description = Sends a GNOME desktop notification when an alert fires.
icon_path = notification.png
payload_format = json

param.title = <string>
param.message = <string>
param.urgency = <list> Default:normal
param.icon = <string>

